<?php
function lp_import_export_menu() {
  $items = array();
  $items['admin/content/import'] = array(
    'title' => t('Product import'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lp_import_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'lp_import_export.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/content/export'] = array(
    'title' => t('Product export'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lp_export_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'lp_import_export.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Batch operation
 */

function lp_import_export_process_import ($row, $fields, $categories, $tags, $vendors, $types, &$context) {
  global $user;
  $err_vend = false;
  $err_cat = false;
  if (isset($context['results']['total'])) {$context['results']['total']++;}  else {$context['results']['total'] = 1;}
  if((empty($row['field_brand']) || !isset($vendors[$row['field_brand']])) && $row['type']!='Модификации'){
    $err_vend = true;
  }
  if((empty($row['field_category']) || !isset($categories[$row['field_category']])) &&  ($row['type']!='Модификации' && $row['type']!='Аксессуар')){
    $err_cat = true;
  }
    $error = empty($row['model'])
      || empty($row['type']) || !isset($types[$row['type']])
      || $err_cat
      || $err_vend;
    if ($error) {
      $context['results']['ignored'][] = "{$row['model']}";
     return;
    }

    $product = db_select('uc_products', 'p')
      ->fields('p')
      ->condition('p.model', $row['model'])
      ->execute()->fetch();

    if (empty($product)) {
      $node = new stdClass;
      $node->shippable = false;
      $node->language = 'ru';
      $node->uid = $user->uid;
      $node->type = $types[$row['type']];
      $new = true;
    } else {
      $node = node_load($product->nid);
      $new = false;
    }

    foreach ($row as $field => $value) {
      if(!empty($value)){
        switch ($fields[$field]['type']) {
          case 'raw':
            if ($field != 'type') $node->$field = $value;
            break;
          case 'text_textarea_with_summary':
            $node->{$field}[LANGUAGE_NONE][0] = array(
              'value' => $value,
              'format' => 'full_html',
              );
          break;
          case 'text_textfield':
          case 'options_buttons':
          case 'number':
          $val_array = explode(';', $value);
          foreach ($val_array as $key => $val) {
            $node->{$field}[LANGUAGE_NONE][$key]['value'] = trim($val);
          }
          break;
          case 'taxonomy_autocomplete' :
          case 'term_reference_tree' :
            switch ($field) {
            case 'field_brand':
              $node->field_brand[LANGUAGE_NONE][0]['tid'] = $vendors[$value];
              break;
            case 'field_category':
              $node->field_category[LANGUAGE_NONE][0]['tid'] = $categories[$value];
              break;
            case 'field_tags':
              $terms = preg_split('/\s*,\s*//*', $value);
            $node->field_tags[LANGUAGE_NONE] = array();
            foreach ($terms as $term_name) {
              if (!isset($tags[$term_name])) {
                $term = taxonomy_get_term_by_name($term_name, 'tags');
                if (empty($term)) {
                  $term = new stdClass;
                  $term->vid = $tags_vocabulary->vid;
                  $term->name = $term_name;
                  taxonomy_term_save($term);
                } else {
                  $term = array_shift($term);
                }
                $tags[$term_name] = $term->tid;
              }
              $node->field_tags[LANGUAGE_NONE][] = array('tid' => $tags[$term_name]);
            }
              break;

            default:
              # code...
              break;
          }
          break;
          case 'image_image':
            if (empty($node->uc_product_image)) {
              $filepath = 'http://teploexpert.com' . $value;
              $mime_raw = explode('.', $value);
              $mime = array_pop($mime_raw);
              $land = 'public://'. $node->model . '.' . $mime;
              if (copy($filepath, $land)) {
                $file = new stdClass;
                $file->uid = $user->uid;
                $file->uri = $land;
                $file->filename = $node->model . '.' . $mime;
                $file->filemime = $mime;
                $file->status = 1;
                file_save($file);

                $node->uc_product_image[LANGUAGE_NONE][0] = (array) $file;
                break;
              }
          }
            break;
          default:
            # code...
            break;
        }
      }
    }

    if($node->type == 'mod') $node->status = 0;
    node_save($node);
    if($node->type == 'mod'){
      $node = node_load($node->nid);
    $option = new stdClass;
      $option->aid = 1;
      $option->name = $node->title;
      $option->cost = $node->cost;
      $option->price = $node->sell_price;
     $opt_query = db_select('uc_product_as_attribute_option', 'u')
     ->fields('u', array('oid'))
     ->condition('u.nid', $node->nid)
     ->execute()
     ->fetchField();
     if(!empty($opt_query)) $option->oid = $opt_query;
      uc_attribute_option_save($option);
      uc_product_as_attribute_option_save($option->oid, $node->nid);
    }
    if (!isset($context['results']['created'])) $context['results']['created'] = 0;
    if (!isset($context['results']['updated'])) $context['results']['updated'] = 0;
    if ($new) {
      $context['results']['created']++;
    } else {
      $context['results']['updated']++;
    }

    /*foreach ($related_fields as $field) {
      $row[$field] = trim($row[$field]);
      if (!empty($row[$field])) {
        $node_models = preg_split('/\s*,\s*//*', $row[$field], -1, PREG_SPLIT_NO_EMPTY);
        if (empty($node_models)) {
            continue;
        }
        $models = array_merge($models, $node_models);
        $product_related_models[$node->nid][$field] = $node_models;
      }
    }*/
  }

  if(!empty($models)){$models = array_unique($models);
  //$nids = array_unique($nids);
  $result = db_select('uc_products', 'p')
    ->fields('p', array('nid', 'model'))
    ->condition('p.model', $models, 'IN')
    ->execute()->fetchAll();
  $nids = array();
  foreach ($result as $row) {
    $nids[$row->model] = $row->nid;
  }
  foreach ($product_related_models as $nid => $node_models) {
    $node = node_load($nid);
    foreach ($related_fields as $field) {
      $values = array();
    if (isset($node_models[$field])) {
      foreach ($node_models[$field] as $model) {
      if (isset($nids[$model])) {
        $values[] = array('nid' => $nids[$model]);
      }
      }
      $node->{$field}[LANGUAGE_NONE] = $values;
    }

    }
    node_save($node);
  }
}

function lp_import_export_process_import_finished ($success, $results, $operations) {

  drupal_set_message(t('@total products in file. @created products were created, @updated products were updated.', array(
    '@total' => $results['total'],
    '@created' => $results['created'],
    '@updated' => $results['updated'],
  )));
  if (!empty($results['ignored'])) {
    drupal_set_message(t('The following SKUs were ignored (row. model): !ignored', array(
      '!ignored' => '<br />' . implode('<br />', $results['ignored']),
    )), 'error');
  }
}